language: node_js
node_js:
  - 0.10

notifications:
  irc:
    channels:
      - "irc.freenode.org#ubuntu-si"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"